FROM ubuntu:14.04
MAINTAINER kevenking <kevenking@gmail.com>

RUN apt-get update
RUN apt-get install -y python python-pip python-dev libxml2-dev libxslt-dev libffi-dev libssl-dev

RUN pip install --upgrade pip
